# Json to CSV file
## Graduation project - Annemijn Portier
------
For this study, a dataset is provided from the finance company Geld.nl. The dataset contains behavioral data of customers that have applied for a loan on the Geld.nl website.The dataset that has been supplied contains data from March 2019 till May 2020. The datasets are delivered in separate files per week and are in JSON format. In this Notebook, the different data files are merged into one dataset and converted into a CSV format.

In [4]:
import pandas as pd
import numpy as np 
import json 
from pandas.io.json import json_normalize #package for flattening json in pandas df

----
## Normalizing Json files

First I loaded the json files into the Notebook. Then I created different dataframes with the normalized json files.

In [12]:
#load json object
with open('data4/1.json',encoding='utf-8') as f:
    d = json.load(f)

#lets put the data into a pandas df
df = json_normalize(d) #normalize json data into dataframe
df.head() #show the resulting data

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.minimalInterest,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,zRmt0nEB-Xac5m6UZnUP,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,Clickout,False,False,[],www.geld.nl,60,1.5,Anders,PL,2500,"9,15",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,Santander,3.0,Rente,af591ad8-3d6b-499d-b4c7-9f1fa8c35f6f,2020/05/01 23:55:05,2020/05/01 23:58:31,2020-05-01T23:58:31.294000,_doc,[1588377511294]
1,a5ur0nEBM8lHFtZNW2lx,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,Aanvraagstraat,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,"6,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:56:08,2020-05-01T23:56:17.586000,_doc,[1588377377586]
2,CJur0nEBM8lHFtZNO2l4,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,"6,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:56:08,2020-05-01T23:56:08.958000,_doc,[1588377368958]
3,jBmr0nEB-Xac5m6UD3XD,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,2500,"9,15",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,af591ad8-3d6b-499d-b4c7-9f1fa8c35f6f,2020/05/01 23:55:05,2020/05/01 23:55:58,2020-05-01T23:55:58.170000,_doc,[1588377358170]
4,o5ur0nEBM8lHFtZND2gi,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,"6,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:55:58,2020-05-01T23:55:58.067000,_doc,[1588377358067]
5,U5uq0nEBM8lHFtZNEWb_,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,"6,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:54:53,2020-05-01T23:54:53.193000,_doc,[1588377293193]
6,_xmn0nEB-Xac5m6UDnSE,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,Clickout,False,False,[],www.geld.nl,60,1.5,Lening oversluiten,PL,8000,"5,7",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,ABN AMRO,4.0,Rente,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,2020/05/01 23:44:21,2020/05/01 23:51:35,2020-05-01T23:51:35.570000,_doc,[1588377095570]
7,uJul0nEBM8lHFtZNClln,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,5000,"6,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,3921876e-66da-4594-886e-2ebfce2f7fcf,2020/05/01 23:48:24,2020/05/01 23:49:22,2020-05-01T23:49:23.058000,_doc,[1588376963058]
8,jpuk0nEBM8lHFtZNqljY,geld_leenmodule,None,Lender & Spender,Ja,e71c4394-4287-4b35-a300-de83d39a4e7e,1.5,Aanvraagstraat - Stap 2,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,None,None,Man,Nee,NaN,8000.0,Persoonlijke lening,60.0,Persoonlijke lening,3200.0,NaN,None,None,1.0,Noord-Brabant,5.7,Rente,2020-05-01T23:49:05.000000,PERMANENT_FULLTIME,None,Loondienst,None,None,None,Breda,1.0,39,Aanvraagstraat - Stap 3,False,False,[],www.geld.nl,60,1.5,Lening oversluiten,PL,8000,"5,7",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,2020/05/01 23:44:21,2020/05/01 23:45:43,2020-05-01T23:49:05.000000,_doc,[1588376945000]
9,qxmk0nEB-Xac5m6UbnSj,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,resultaten,False,False,[],www.geld.nl,36,1.5,Auto,PL,5000,"5,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,018483c5-245b-4329-b9fc-c33bd3705408,2020/05/01 23:47:53,2020/05/01 23:48:46,2020-05-01T23:48:46.673000,_doc,[1588376926673]
10,fZuj0nEBM8lHFtZNbFUk,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,Clickout,False,False,[],www.geld.nl,60,1.0,Verbouwing,PL,10000,"5,3",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,ABN AMRO,1.0,Rente,4724906f-4216-48e4-946a-baf019e007db,2020/05/01 23:45:55,2020/05/01 23:47:39,2020-05-01T23:47:39.079000,_doc,[1588376859079]
11,G5uj0nEBM8lHFtZNU1Ww,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,resultaten,False,False,[],www.geld.nl,60,1.0,Verbouwing,PL,10000,"5,3",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,4724906f-4216-48e4-946a-baf019e007db,2020/05/01 23:45:55,2020/05/01 23:47:32,2020-05-01T23:47:32.829000,_doc,[1588376852829]
12,uZuj0nEBM8lHFtZNJlRd,geld_leenmodule,None,Lender & Spender,Nee,e71c4394-4287-4b35-a300-de83d39a4e7e,1.5,Aanvraagstraat - Stap 1,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,None,None,Man,Nee,NaN,8000.0,Persoonlijke lening,60.0,Persoonlijke lening,NaN,NaN,None,None,1.0,Noord-Brabant,5.7,Rente,2020-05-01T23:47:25.000000,,None,Loondienst,None,None,None,Breda,1.0,39,Aanvraagstraat - Stap 1,False,False,[],www.geld.nl,60,1.5,Lening oversluiten,PL,8000,"5,7",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,2020/05/01 23:44:21,2020/05/01 23:45:43,2020-05-01T23:47:25.000000,_doc,[1588376845000]
13,WJui0nEBM8lHFtZN81Rk,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,resultaten,False,False,[],www.geld.nl,60,1.0,Verbouwing,PL,10000,"5,3",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,4724906f-4216-48e4-946a-baf019e007db,2020/05/01 23:45:55,2020/05/01 23:47:08,2020-05-01T23:47:08.167000,_doc,[1588376828167]
14,lZui0nEBM8lHFtZNrVPe,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,15000,"4,4",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '15000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,b4209b99-2b90-48d8-a579-12ede7c6453f,2020/05/01 23:46:13,2020/05/01 23:46:48,2020-05-01T23:46:48.747000,_doc,[1588376808747]
15,bBmi0nEB-Xac5m6UlnQk,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,resultaten,False,False,[],www.geld.nl,60,1.0,Verbouwing,DK,10000,0,False,False,False,False,NaN,"[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,4724906f-4216-48e4-946a-baf019e007db,2020/05/01 23:45:55,2020/05/01 23:46:44,2020-05-01T23:46:44.293000,_doc,[1588376804293]
16,Yxmi0nEB-Xac5m6UZXQO,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,resultaten,False,False,[],www.geld.nl,60,1.0,Verbouwing,DK,10000,0,False,False,False,False,NaN,"[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,4724906f-4216-48e4-946a-baf019e007db,2020/05/01 23:45:55,2020/05/01 23:46:31,2020-05-01T23:46:31.578000,_doc,[1588376791578]
17,qpuh0nEBM8lHFtZN5VHA,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,Aanvraagstraat,False,False,[],www.geld.nl,60,1.5,Lening oversluiten,PL,8000,"5,7",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,2020/05/01 23:44:21,2020/05/01 23:45:43,2020-05-01T23:45:57.519000,_doc,[1588376757519]
18,RZuh0nEBM8lHFtZNr1F9,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,resultaten,False,False,[],www.geld.nl,60,1.5,Lening oversluiten,PL,8000,"5,7",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,a64e2c8a-e27e-4f59-97b7-ac35c5d619b6,2020/05/01 23:44:21,2020/05/01 23:45:43,2020-05-01T23:45:43.521000,_doc,[1588376743521]
19,WpuZ0nEBM8lHFtZNxz0X,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,Clickout,False,False,[],www.geld.nl,36,1.5,Anders,PL,1500,"11,9",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '1500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,Santander,1.0,Rente,5e8173d0-04a6-43d4-8480-dc08a4c5a54c,2020/05/01 23:35:56,2020/05/01 23:37:05,2020-05-01T23:37:05.485000,_doc,[1588376225485]
20,-ZuZ0nEBM8lHFtZNmjxb,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,resultaten,False,False,[],www.geld.nl,36,1.5,Anders,PL,1500,"11,9",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '1500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,5e8173d0-04a6-43d4-8480-dc08a4c5a54c,2020/05/01 23:35:56,2020/05/01 23:36:53,2020-05-01T23:36:53.951000,_doc,[1588376213951]
21,6hmR0nEB-Xac5m6U5nGE,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,resultaten,False,False,[],www.geld.nl,120,1.5,Boot,PL,45000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '45000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,37bd1b5d-56b3-4a88-a9ed-97baba61e7da,2020/05/01 23:24:40,2020/05/01 23:28:30,2020-05-01T23:28:30.542000,_doc,[1588375710542]
22,4RmR0nEB-Xac5m6Up3H3,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,resultaten,False,False,[],www.geld.nl,120,1.5,Verbouwing,PL,50000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '50000', 'resulttext': '', 'name':...",0,Rente,Freo,Persoonlijke lening,1.0,Rente,None,NaN,None,a97789ff-9829-4b72-9c0a-fb88cd0696ae,2020/05/01 23:18:28,2020/05/01 23:20:10,2020-05-01T23:28:11.413000,_doc,[1588375691413]
23,kRmP0nEB-Xac5m6UI3Hv,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,resultaten,False,False,[],www.geld.nl,120,1.5,Boot,PL,45000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '45000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,37bd1b5d-56b3-4a88-a9ed-97baba61e7da,2020/05/01 23:24:40,2020/05/01 23:25:27,2020-05-01T23:25:28.562000,_doc,[1588375528562]
24,KJuM0nEBM8lHFtZNTBvW,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,resultaten,False,False,[],www.geld.nl,12,1.5,Auto,PL,10000,"5,2",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,6f84abc7-ad2d-4f12-a8a2-399aa0e68378,2020/05/01 23:21:50,2020/05/01 23:22:22,2020-05-01T23:22:22.180000,_doc,[1588375342180]
25,5RmK0nEB-Xac5m6UzHDP,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,Aanvraagstraat,False,False,[],www.geld.nl,120,1.5,Verbouwing,PL,50000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '50000', 'resulttext': '', 'name':...",0,Rente,Freo,Persoonlijke lening,1.0,Rente,None,NaN,None,a97789ff-9829-4b72-9c0a-fb88cd0696ae,2020/05/01 23:18:28,2020/05/01 23:20:10,2020-05-01T23:20:43.228000,_doc,[1588375243228]
26,VZuK0nEBM8lHFtZNrxcb,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,Aanvraagstraat,False,False,[],www.geld.nl,120,1.5,Auto,PL,8000,"6,0",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,Directa.nl,Persoonlijke lening,1.0,Rente,None,NaN,None,aec79a4d-ed1e-4e52-a8aa-53a304a8f2b4,2020/05/01 23:19:40,2020/05/01 23:20:10,2020-05-01T23:20:32.812000,_doc,[1588375232812]
27,0RmK0nEB-Xac5m6UUHD9,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,resultaten,False,False,[],www.geld.nl,120,1.5,Verbouwing,PL,50000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '50000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,a97789ff-9829-4b72-9c0a-fb88cd0696ae,2020/05/01 23:18:28,2020/05/01 23:20:10,2020-05-01T23:20:11.387000,_doc,[1588375211387]
28,0hmK0nEB-Xac5m6UVnAM,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,resultaten,False,False,[],www.geld.nl,120,1.5,Auto,PL,8000,"6,0",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '8000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,aec79a4d-ed1e-4e52-a8aa-53a304a8f2b4,2020/05/01 23:19:40,2020/05/01 23:20:10,2020-05-01T23:20:10.116000,_doc,[1588375210116]
29,2ZuH0nEBM8lHFtZNaQ7T,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,resultaten,False,False,[],www.geld.nl,120,1.5,Restschuld hypotheek,PL,72000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '72000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,77b36f3d-7344-4014-a8bf-9369be3f8bbc,2020/05/01 23:12:34,2020/05/01 23:17:01,2020-05-01T23:17:01.371000,_doc,[1588375021371]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,f406zXEBM8lHFtZNNqRy,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,DK,16000,"4,7",False,False,False,False,"[{'ProductNaam': 'Doorlopend krediet', 'Positi...","[{'result': '16000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,b5cbb727-87df-4c4e-848c-08d18f502424,2020/04/30 22:30:54,2020/04/30 22:34:37,2020-04-30T22:34:37.918000,_doc,[1588286077918]
1971,X403zXEBM8lHFtZNtZ76,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,Aanvraagstraat,False,False,[],www.geld.nl,12,1.5,Auto,PL,6950,"6,5",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '6950', 'resulttext': '', 'name': ...",0,Rente,Freo,Persoonlijke lening,1.0,Rente,None,NaN,None,4a149d23-d7b4-47f3-9769-96307ec37258,2020/04/30 22:29:00,2020/04/30 22:31:12,2020-04-30T22:31:50.337000,_doc,[1588285910337]

In [13]:
#load json object
with open('data4/2.json',encoding='utf-8') as f:
    d2 = json.load(f)

#lets put the data into a pandas df
df2 = json_normalize(d2) #normalize json data into dataframe
df2.head() #show the resulting data

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.loanValueString,_source.minimalInterest,_source.navigateFromLoanType,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.resultsCount,_source.resultsCountTopX,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,CItCzHEBM8lHFtZNMi8s,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,resultaten,False,False,[],www.geld.nl,36,1.5,Auto,PL,26000,NaN,"3,8",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '26000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,2ba3fbdd-74c5-4caa-bdb7-fdeb9bf0fdb4,2020/04/30 18:02:16,2020/04/30 18:03:40,2020-04-30T18:03:41.253000,_doc,[1588269821253]
1,zYtAzHEBM8lHFtZNhSqc,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,resultaten,False,False,[],www.geld.nl,120,1.5,Boot,PL,70000,NaN,"3,8",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '70000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,7d75fc10-3907-4352-b9be-8fd06252987f,2020/04/30 18:01:18,2020/04/30 18:01:52,2020-04-30T18:01:52.673000,_doc,[1588269712673]
2,xxgFzHEB-Xac5m6ULnNW,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,Clickout,False,True,[363],www.geld.nl,36,1.0,Auto,PL,1500,NaN,"11,9",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '1500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,Santander,1.0,Rente,a439d117-d75f-40c7-8c21-3d79e96b1b9b,2020/04/30 17:54:44,2020/04/30 18:00:22,2020-04-30T18:00:22.533000,_doc,[1588269622533]
3,3Is_zHEBM8lHFtZNCSY4,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,resultaten,False,False,[],www.geld.nl,60,1.0,Anders,DK,20000,NaN,"4,7",NaN,False,False,False,False,"[{'ProductNaam': 'Doorlopend krediet', 'Positi...",NaN,NaN,"[{'result': '20000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,6062e140-9162-4336-9416-27859ae10750,2020/04/30 17:59:33,2020/04/30 18:00:14,2020-04-30T18:00:15.122000,_doc,[1588269615122]
4,GYs9zHEBM8lHFtZN8CRF,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,30000,NaN,"3,8",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '30000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,67a783e8-0906-4c86-b989-bb26a7c82cbd,2020/04/30 17:57:40,2020/04/30 17:59:04,2020-04-30T17:59:04.858000,_doc,[1588269544858]

In [14]:
#load json object
with open('data4/3.json',encoding='utf-8') as f:
    d3 = json.load(f)

#lets put the data into a pandas df
df3 = json_normalize(d3) #normalize json data into dataframe
df3.head() #show the resulting data

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.minimalInterest,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,zn4Vx3EBM8lHFtZNOg4P,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,10000,"5,1",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,ba49c7c7-b78c-4532-aef7-f36b9c48739c,2020/04/29 17:43:36,2020/04/29 17:56:28,2020-04-29T17:56:28.469000,_doc,[1588182988469]
1,hBcVx3EB-Xac5m6ULa4v,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,resultaten,False,False,[],www.geld.nl,12,1.5,Verbouwing,PL,3750,"9,15",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '3750', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,3e107ee0-77dc-437d-81aa-975361c0b70a,2020/04/29 17:56:00,2020/04/29 17:56:25,2020-04-29T17:56:25.631000,_doc,[1588182985631]
2,9n4Ux3EBM8lHFtZN8Q2y,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,10000,"5,1",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,ba49c7c7-b78c-4532-aef7-f36b9c48739c,2020/04/29 17:43:36,2020/04/29 17:56:09,2020-04-29T17:56:09.951000,_doc,[1588182969951]
3,bxcUx3EB-Xac5m6Uwa5K,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,PL,10000,"5,1",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,ba49c7c7-b78c-4532-aef7-f36b9c48739c,2020/04/29 17:43:36,2020/04/29 17:55:57,2020-04-29T17:55:57.524000,_doc,[1588182957524]
4,0n4Ux3EBM8lHFtZNkwyF,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,resultaten,False,False,[],www.geld.nl,60,1.5,Auto,DK,25000,"4,5",False,False,False,False,"[{'ProductNaam': 'Flexibele Lening Premium', '...","[{'result': '25000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,5a9e1bb8-7a59-4a50-8b1d-cf8f70695a76,2020/04/29 17:55:24,2020/04/29 17:55:46,2020-04-29T17:55:46.553000,_doc,[1588182946553]

In [15]:
#load json object
with open('data4/4.json',encoding='utf-8') as f:
    d4 = json.load(f)

#lets put the data into a pandas df
df4 = json_normalize(d4) #normalize json data into dataframe
df4.head() #show the resulting data

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.minimalInterest,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,929jwXEBM8lHFtZNTqCy,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,resultaten,False,False,[],www.geld.nl,180,1.5,Verbouwing,PL,50000,0,False,False,False,False,NaN,"[{'result': '50000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,d1bfbcfb-70dc-4f6c-8757-c4d8f3c62738,2020/04/28 15:23:07,2020/04/28 15:24:03,2020-04-28T15:24:03.098000,_doc,[1588087443098]
1,jW9jwXEBM8lHFtZNI6D2,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,resultaten,False,False,[],www.geld.nl,24,1.5,Anders,PL,1500,"11,9",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '1500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,a5ef4edd-6365-4c19-b248-a9a6bef87f59,2020/04/28 15:22:22,2020/04/28 15:23:52,2020-04-28T15:23:52.723000,_doc,[1588087432723]
2,hhZiwXEB-Xac5m6UJ824,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,resultaten,False,False,[],www.geld.nl,60,2.0,Lening oversluiten,DK,2500,"9,7",False,False,False,False,"[{'ProductNaam': 'Doorlopend krediet', 'Positi...","[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,dd71e57a-ad66-4c66-9663-7b22af6f51db,2020/04/28 15:20:38,2020/04/28 15:22:50,2020-04-28T15:22:51.027000,_doc,[1588087371027]
3,eBZhwXEB-Xac5m6Uv81q,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,resultaten,False,False,[],www.geld.nl,60,2.0,Lening oversluiten,DK,2500,"9,7",False,False,False,False,"[{'ProductNaam': 'Doorlopend krediet', 'Positi...","[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,dd71e57a-ad66-4c66-9663-7b22af6f51db,2020/04/28 15:20:38,2020/04/28 15:22:24,2020-04-28T15:22:24.282000,_doc,[1588087344282]
4,bRZhwXEB-Xac5m6Ub81V,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,resultaten,False,False,[],www.geld.nl,60,1.5,Verbouwing,PL,25000,"3,8",False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...","[{'result': '25000', 'resulttext': '', 'name':...",0,Rente,None,None,NaN,None,None,NaN,None,e1b9951d-cd2e-4c20-97f4-436276d2c7b8,2020/04/28 15:21:29,2020/04/28 15:21:59,2020-04-28T15:21:59.832000,_doc,[1588087319832]

Then I put the different dataframes into one dataframe.

In [95]:
pdList = [df, df2, df3, df4]
df_subset = pd.concat(pdList)

df_subset.head()

C:\Users\annem\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.loanValueString,_source.minimalInterest,_source.navigateFromLoanType,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.resultsCount,_source.resultsCountTopX,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,zRmt0nEB-Xac5m6UZnUP,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,Clickout,False,False,[],www.geld.nl,60,1.5,Anders,PL,2500,NaN,"9,15",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,Santander,3.0,Rente,af591ad8-3d6b-499d-b4c7-9f1fa8c35f6f,2020/05/01 23:55:05,2020/05/01 23:58:31,2020-05-01T23:58:31.294000,_doc,[1588377511294]
1,a5ur0nEBM8lHFtZNW2lx,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Aanvraagstraat,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,NaN,"6,2",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:56:08,2020-05-01T23:56:17.586000,_doc,[1588377377586]
2,CJur0nEBM8lHFtZNO2l4,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,NaN,"6,2",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:56:08,2020-05-01T23:56:08.958000,_doc,[1588377368958]
3,jBmr0nEB-Xac5m6UD3XD,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,2500,NaN,"9,15",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '2500', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,af591ad8-3d6b-499d-b4c7-9f1fa8c35f6f,2020/05/01 23:55:05,2020/05/01 23:55:58,2020-05-01T23:55:58.170000,_doc,[1588377358170]
4,o5ur0nEBM8lHFtZND2gi,geld_leenmodule,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,resultaten,False,False,[],www.geld.nl,60,1.5,Anders,PL,5000,NaN,"6,2",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '5000', 'resulttext': '', 'name': ...",0,Rente,None,None,NaN,None,None,NaN,None,6f792b3f-0ec1-4a67-b254-54a1676d68fd,2020/05/01 23:54:02,2020/05/01 23:55:58,2020-05-01T23:55:58.067000,_doc,[1588377358067]

----
## Data cleaning
**Double rows**
There are rows with the same values in the dataframe. This is because every time the person changes something on the website, the data creates a new row. That is why I have removed the double rows based on the clickref. This is an unique ID of the person applying for a loan.

**notna()** Then I removed all the rows that have NaN as value at the column provider. These customers did not apply for a loan.

In [97]:
df_subset = df_subset.drop_duplicates(subset='_source.statistics.clickref', keep='first') #delete duplicate data and keep the first one of the duplicates.
df_subset = df_subset[df_subset['_source.Aanvraag.Aanbiedernaam'].notna()]
df_subset = df_subset.reset_index(drop=True) #Reset the index after dropna
df_subset.head()

,_id,_index,_score,_source.Aanvraag.Aanbiedernaam,_source.Aanvraag.AanvraagAfgerond,_source.Aanvraag.AanvraagGUID,_source.Aanvraag.Aflossingspercentage,_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat,_source.Aanvraag.Clickref,_source.Aanvraag.ContractfaseUitzendcontract,_source.Aanvraag.ContractfaseUitzendcontractPartner,_source.Aanvraag.Geslacht,_source.Aanvraag.Kinderen,_source.Aanvraag.LeeftijdPartner,_source.Aanvraag.Leenbedrag,_source.Aanvraag.Leenvorm,_source.Aanvraag.Looptijd,_source.Aanvraag.NaamProduct,_source.Aanvraag.NettoInkomen,_source.Aanvraag.NettoInkomenPartner,_source.Aanvraag.OprichtingsDatumOnderneming,_source.Aanvraag.OprichtingsDatumOndernemingPartner,_source.Aanvraag.PositieID,_source.Aanvraag.Provincie,_source.Aanvraag.Rente,_source.Aanvraag.SorteringDieActiefWas,_source.Aanvraag.Timestamp,_source.Aanvraag.TypeContract,_source.Aanvraag.TypeContractPartner,_source.Aanvraag.TypeInkomen,_source.Aanvraag.TypeInkomenPartner,_source.Aanvraag.TypeOnderneming,_source.Aanvraag.TypeOndernemingPartner,_source.Aanvraag.Woonplaats,_source.PositieID,_source.age,_source.analytics,_source.closureViaGeldNl,_source.compareActive,_source.compareIds,_source.hostname,_source.loanDuration,_source.loanPercentage,_source.loanPurpose,_source.loanType,_source.loanValue,_source.loanValueString,_source.minimalInterest,_source.navigateFromLoanType,_source.orvIncluded,_source.penaltyFreeRelay,_source.refinance,_source.refinanceLoanPossible,_source.result,_source.resultsCount,_source.resultsCountTopX,_source.scenario,_source.sorting,_source.sortingName,_source.statistics.aanvraag_aname,_source.statistics.aanvraag_pname,_source.statistics.aanvraag_positieid,_source.statistics.aanvraag_sorting,_source.statistics.clickout_aname,_source.statistics.clickout_positieid,_source.statistics.clickout_sorting,_source.statistics.clickref,_source.statistics.firstupdate,_source.statistics.lastupdate,_source.timestamp,_type,sort
0,MZpW0nEBM8lHFtZNspRk,geld_leenmodule,None,Lender & Spender,Ja,08ee0aa7-fd30-4578-8af4-77fc27e8ae42,1.5,Aanvraagstraat - Stap 2,53c11431-5317-461f-89c5-ed4c5f66498e,None,None,Man,Nee,NaN,10000.0,Persoonlijke lening,24.0,Persoonlijke lening,2250.0,NaN,None,None,1.0,Friesland,5.1,Rente,2020-05-01T22:23:54.000000,TEMP_FULLTIME,None,Loondienst,None,None,None,Rotsterhaule,1.0,33.0,Aanvraagstraat - Stap 3,False,False,[],www.geld.nl,24,1.5,Restschuld hypotheek,PL,10000,NaN,"5,1",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,53c11431-5317-461f-89c5-ed4c5f66498e,2020/05/01 22:19:16,2020/05/01 22:20:10,2020-05-01T22:23:54.000000,_doc,[1588371834000]
1,xxk00nEB-Xac5m6UtGTX,geld_leenmodule,None,Interbank,Nee,f67e4cdf-c350-446f-a6ca-60624f8d7a21,1.5,Aanvraagstraat - Stap 1,1563cca5-4d3d-4c01-82ec-adbe75c5ce32,None,None,Vrouw,Nee,NaN,23000.0,Persoonlijke lening,36.0,Persoonlijke lening,NaN,NaN,None,None,1.0,Zuid-Holland,4.4,Rente,2020-05-01T21:46:46.000000,None,None,Pensioen,None,None,None,'s-Gravenhage,1.0,71.0,Aanvraagstraat - Stap 1,False,False,[],www.geld.nl,36,1.5,Anders,PL,23000,NaN,"4,4",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '23000', 'resulttext': '', 'name':...",0,Rente,Interbank,Persoonlijke lening,1.0,Rente,None,NaN,None,1563cca5-4d3d-4c01-82ec-adbe75c5ce32,2020/05/01 21:43:11,2020/05/01 21:44:16,2020-05-01T21:46:46.000000,_doc,[1588369606000]
2,LBkc0nEB-Xac5m6UdGH8,geld_leenmodule,None,Lender & Spender,Ja,2f95a56d-f236-42f2-9a08-7422ccc9a002,1.5,Aanvraagstraat - Stap 2,b64469fa-20d2-4226-b64f-90485b4df7c0,None,None,Man,Ja,53.0,6500.0,Persoonlijke lening,60.0,Persoonlijke lening,2350.0,1650.0,None,None,1.0,Zeeland,6.2,Rente,2020-05-01T21:20:18.000000,PERMANENT_FULLTIME,PERMANENT_PARTTIME,Loondienst,Loondienst,None,None,Bruinisse,1.0,48.0,Aanvraagstraat - Stap 3,False,False,[],www.geld.nl,60,1.5,Auto,PL,6500,NaN,"6,2",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '6500', 'resulttext': '', 'name': ...",0,Rente,Lender & Spender,Persoonlijke lening,1.0,Rente,None,NaN,None,b64469fa-20d2-4226-b64f-90485b4df7c0,2020/05/01 21:17:43,2020/05/01 21:18:08,2020-05-01T21:20:18.000000,_doc,[1588368018000]
3,9Bkb0nEB-Xac5m6UD2Bx,geld_leenmodule,None,Freo,Ja,c78cb231-7b79-4ffc-b51c-35c56035d659,1.5,Aanvraagstraat - Stap 2,f44a0bba-cf88-482c-8b08-4e5a35849a1e,None,None,Man,Ja,32.0,10000.0,Persoonlijke lening,120.0,Persoonlijke lening,1900.0,1000.0,None,None,1.0,Zuid-Holland,5.2,Rente,2020-05-01T21:18:46.000000,TEMP_FULLTIME,None,Loondienst,Uitkering,None,None,Spijkenisse,1.0,36.0,Aanvraagstraat - Stap 3,False,False,[],www.geld.nl,120,1.5,Restschuld hypotheek,PL,10000,NaN,"5,2",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '10000', 'resulttext': '', 'name':...",0,Rente,Freo,Persoonlijke lening,1.0,Rente,None,NaN,None,f44a0bba-cf88-482c-8b08-4e5a35849a1e,2020/05/01 21:13:51,2020/05/01 21:14:46,2020-05-01T21:18:46.000000,_doc,[1588367926000]
4,wRnh0XEB-Xac5m6UeVhr,geld_leenmodule,None,Findio,Ja,2406fb58-83d3-47a9-84c5-ad99f68cc285,1.5,Aanvraagstraat - Stap 2,c40d8d21-1b16-4076-b46e-a16a7f82821c,None,None,Man,Nee,NaN,20000.0,Persoonlijke lening,120.0,Persoonlijke Lening Zelfstandigen,NaN,NaN,01-01-2020,None,3.0,Zuid-Holland,4.9,Rente,2020-05-01T20:15:53.000000,None,None,Eigen bedrijf,None,Eenmanszaak,None,Zoetermeer,3.0,23.0,Aanvraagstraat - Stap 3,False,False,[],www.geld.nl,120,1.5,Anders,PL,20000,NaN,"4,6",NaN,False,False,False,False,"[{'ProductNaam': 'Persoonlijke lening', 'Posit...",NaN,NaN,"[{'result': '20000', 'resulttext': '', 'name':...",0,Rente,Findio,Persoonlijke Lening Zelfstandigen,3.0,Rente,None,NaN,None,c40d8d21-1b16-4076-b46e-a16a7f82821c,2020/05/01 20:02:47,2020/05/01 20:05:06,2020-05-01T20:15:53.000000,_doc,[1588364153000]

In [100]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13922 entries, 0 to 9060
Data columns (total 72 columns):
_id                                                            13922 non-null object
_index                                                         13922 non-null object
_score                                                         0 non-null object
_source.Aanvraag.Aanbiedernaam                                 13922 non-null object
_source.Aanvraag.AanvraagAfgerond                              13922 non-null object
_source.Aanvraag.AanvraagGUID                                  13922 non-null object
_source.Aanvraag.Aflossingspercentage                          13922 non-null float64
_source.Aanvraag.BijWelkeVraagIsAfgehaaktInDeAanvraagstraat    13922 non-null object
_source.Aanvraag.Clickref                                      13922 non-null object
_source.Aanvraag.ContractfaseUitzendcontract                   329 non-null object
_source.Aanvraag.ContractfaseUitzendcontractPartner            164 non-null object
_source.Aanvraag.Geslacht                                      13769 non-null object
_source.Aanvraag.Kinderen                                      13922 non-null object
_source.Aanvraag.LeeftijdPartner                               6154 non-null float64
_source.Aanvraag.Leenbedrag                                    13922 non-null float64
_source.Aanvraag.Leenvorm                                      13922 non-null object
_source.Aanvraag.Looptijd                                      13922 non-null float64
_source.Aanvraag.NaamProduct                                   13922 non-null object
_source.Aanvraag.NettoInkomen                                  9777 non-null float64
_source.Aanvraag.NettoInkomenPartner                           3731 non-null float64
_source.Aanvraag.OprichtingsDatumOnderneming                   516 non-null object
_source.Aanvraag.OprichtingsDatumOndernemingPartner            367 non-null object
_source.Aanvraag.PositieID                                     11808 non-null float64
_source.Aanvraag.Provincie                                     13820 non-null object
_source.Aanvraag.Rente                                         13922 non-null float64
_source.Aanvraag.SorteringDieActiefWas                         13918 non-null object
_source.Aanvraag.Timestamp                                     13922 non-null object
_source.Aanvraag.TypeContract                                  10408 non-null object
_source.Aanvraag.TypeContractPartner                           2410 non-null object
_source.Aanvraag.TypeInkomen                                   13909 non-null object
_source.Aanvraag.TypeInkomenPartner                            4877 non-null object
_source.Aanvraag.TypeOnderneming                               612 non-null object
_source.Aanvraag.TypeOndernemingPartner                        377 non-null object
_source.Aanvraag.Woonplaats                                    13817 non-null object
_source.PositieID                                              11803 non-null float64
_source.age                                                    13918 non-null float64
_source.analytics                                              13922 non-null object
_source.closureViaGeldNl                                       13918 non-null object
_source.compareActive                                          13918 non-null object
_source.compareIds                                             13918 non-null object
_source.hostname                                               13922 non-null object
_source.loanDuration                                           13918 non-null object
_source.loanPercentage                                         13918 non-null float64
_source.loanPurpose                                            13912 non-null object
_source.loanType                                               13918 non-null object
_source.loanValue                                              13918 non-null object
_source.loanValueString                                        2881 non-null object
_source.minimalInterest                                        13918 non-null object
_source.navigateFromLoanType                                   2886 non-null object
_source.orvIncluded                                            13918 non-null object
_source.penaltyFreeRelay                                       13918 non-null object
_source.refinance                                              13918 non-null object
_source.refinanceLoanPossible                                  13918 non-null object
_source.result                                                 13918 non-null object
_source.resultsCount                                           2886 non-null float64
_source.resultsCountTopX                                       2886 non-null float64
_source.scenario                                               13918 non-null object
_source.sorting                                                13918 non-null object
_source.sortingName                                            11830 non-null object
_source.statistics.aanvraag_aname                              11784 non-null object
_source.statistics.aanvraag_pname                              11784 non-null object
_source.statistics.aanvraag_positieid                          11784 non-null float64
_source.statistics.aanvraag_sorting                            11784 non-null object
_source.statistics.clickout_aname                              162 non-null object
_source.statistics.clickout_positieid                          0 non-null float64
_source.statistics.clickout_sorting                            0 non-null object
_source.statistics.clickref                                    13918 non-null object
_source.statistics.firstupdate                                 13918 non-null object
_source.statistics.lastupdate                                  13918 non-null object
_source.timestamp                                              13922 non-null object
_type                                                          13922 non-null object
sort                                                           13922 non-null object
dtypes: float64(15), object(57)
memory usage: 7.8+ MB

Then I saved the data frame as a CSV file to use it for the notebook *data cleaning, data analysis and machine learning algorithms.ipynb*

In [101]:
df_final.to_csv( "dataset-geldv2.csv", index=False, encoding='utf-8-sig')